### ISSUE TITLE
Shift does not open items in the sidebar

### ISSUE THREAD

**Issue by isosphere** [isosphere/logseq-journals-nextprev#1]
I've examined the code for [logseq-journal-calendar](https://github.com/xyhp915/logseq-journals-calendar) and I don't understand how that plugin accomplishes this feature. The `event` that is checked is always just `{}` 🤔

**Comment by isosphere** [comment]
I think this must automatically pass along `event` with that kind of detail:

https://github.com/xyhp915/logseq-journals-calendar/blob/8f2385cec8db180c4af06e757d25d790b7c0bebd/src/App.vue#L7-L12

`v-bind` is specific to Vue, which isn't what we're using in main.js where we create our buttons. 

https://github.com/isosphere/logseq-journals-nextprev/blob/4984bc27556593d14a482ada2d8ecebaf83d4865/src/main.js#L41-L56

The docs for [registerUIItem](https://logseq.github.io/plugins/interfaces/IAppProxy.html#registerUIItem) don't give any hints. 

If I change `nextDay` and `prevDay` to take a single argument, that argument gets populated with some context information. It doesn't appear to include information that changes if shift is held - there's no `shiftHeld` property. If I add a second argument, it is always `undefined`. [^1]

[^1]: Javascript is a barbaric language.

If we want this feature, I think we have to add a key handler that updates a  global variable which is then checked by the `nextDay` and `prevDay` functions before triggering the action. I don't like it, but it would probably work. However:

> Keyboard events are only generated by `<input>`, `<textarea>`, `<summary>` and anything with the contentEditable or tabindex attribute. If not caught, they [bubble](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling) up the [DOM tree](https://developer.mozilla.org/en-US/docs/Web/API/Document_object_model/Using_the_Document_Object_Model#what_is_a_dom_tree) until they reach [Document](https://developer.mozilla.org/en-US/docs/Web/API/Document).
>
> https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event

I think we'd have to add the event listener to the toolbar items themselves, but that's not accessible within our app: `parent.document.getElementById` always returns `null` within the `mounted () {}` section, even if you wait for 10 seconds (this actually holds up the entire Logseq application with no toolbar buttons visible). I think I can safely conclude that the toolbar items are created after `mounted () {}` is called.

You can't access the buttons via a `.then()` handler on `logseq.ready()`, either - they're always `null`.

**Comment by isosphere** [comment]
I have the shift hooking working in the latest commit: I used a timer to defer the listener attachment until after `mounted() {}` is finished, though I don't love this. I'd rather an explicit event hook that is guaranteed to work at the appropriate time, rather than my arbitrary 1 second delay which is probably fine, but could fail.

When using the shift-click feature though, I'm getting complaints that I'm not providing a UUID. Maybe I'm trying to load stuff in the sidebar the wrong way; maybe we'll have to also query UUIDs.

```javascript
index.html:1 Uncaught (in promise) Error: 2024-01-21 is not a valid UUID string.
    at $logseq$sdk$utils$uuid_or_throw_error$$ (ui.cljs:38:16)
    at br.<anonymous> (api.cljs:588:16)
    at br.R (lsplugin.core.js:2:49447)
    at br.<anonymous> (lsplugin.core.js:2:93340)
    at a.emit (lsplugin.core.js:2:28521)
    at X.<anonymous> (lsplugin.core.js:2:88623)
    at lsplugin.core.js:2:53506
    at Array.forEach (<anonymous>)
    at X.listener (lsplugin.core.js:2:53491)
```

**Comment by isosphere** [comment]
Opening to sidebar requires the UUID, but opening a page via pushState requires the name. It's a weird API, but I got it working. Feature pushed as version 1.2.0.
